### ISSUE TITLE
Support binary-only annotations

### ISSUE THREAD

**Issue by stephenh** [scalagwt/scalagwt-gwt#18]
GWT allows annotations to be loaded from outside the client-side classpath.

**Comment by gkossakowski** [comment]
How this is related to our work?

**Comment by stephenh** [comment]
While normally GWT code can use only classes in the scala-library-gwt/gwt-lang jars, annotations can actually come from regular Java code (e.g. server-side/non-client-side types). This means that a true gwt-lang jar (or similar jars users will have to build for their own projects) should also include annotations in them.

I suppose this just means client-side jars must be built with extra care if binary-only annotations are to be used. I'm not a huge fan of that, but that's okay.

**Comment by gkossakowski** [comment]
Yep, the best is to factor out such annotations into separate jar that both client and server depend on. That's quite reasonable requirement. Can we close this issue?

**Comment by stephenh** [comment]
I personally am not a fan of that (it's not something GWT users have to do today), but, yes, closing it is fine.
