### ISSUE TITLE
Check if Scala interface signatures should include java.lang.Object

### ISSUE THREAD

**Issue by stephenh** [scalagwt/scalagwt-gwt#6]
[TraversableFactory](https://github.com/paulp/scala-full/blob/master/src/library/scala/collection/generic/TraversableFactory.scala), an interface, has a signature of:

`<CC:Lscala/collection/Traversable<Ljava/lang/Object;>;>Lscala/collection/generic/GenTraversableFactory<TCC;>;Lscala/collection/generic/GenericSeqCompanion<TCC;>;Lscala/ScalaObject;`

However, ASM reads this as GenTraversableFactory being the super class, and only GenericSeqCompanion and ScalaObject being the implemented interfaces.

Comments in the GWT TypeOracle lead me to believe that javac signatures for interfaces always have java/lang/Object as the first type, taking up the superclass slot, and then the interfaces after that.

For now I'm hacking around this and adding GenTraversableFactory as an implemented interface, but it might be worth checking with the Scala team about fixing the signature to match the javac output.

(If this does get fixed in Scala, then the hack in GWT's TypeOracle can be removed.)

**Comment by gkossakowski** [comment]
I checked Scala's issue tracker and cannot find a ticket for this problem.

I tried to check what spec says about it and it's not very clear on this. I checked [ClassFileFormat](http://java.sun.com/docs/books/jvms/second_edition/ClassFileFormat-Java5.pdf) document and it does indeed says:

> For an interface, the value of the super_class item must always be a valid index into the constant_pool table.
> The constant_pool entry at that index must be a CONSTANT_Class_info structure representing the class Object.

However, paragraphs about Signature does not discuss this issue at all. From language spec it's not very clear that interfaces have java.lang.Object as a superclass (it's not clear if they have a super class at all).

Could you provide a link to your hack? I'm wondering how it looks like.

**Comment by stephenh** [comment]
https://github.com/stephenh/google-web-toolkit/commit/7699c3020187136bca0940ee490145e563f41306

The original GWT comment is initially what led me to suspect that interfaces always have java/lang/Object first in their signature. I also poked a few java interfaces with javap and it seems to be the case.

**Comment by gkossakowski** [comment]
I finally had time to debug it. It's quite bad problem, see this ticket for details:

https://issues.scala-lang.org/browse/SI-4891

Should be fixed soon, hopefully.

**Comment by stephenh** [comment]
Thanks for following up on that; that does look like a larger problem than I thought it was.

I didn't see the fact that "java/lang/Object" is missing from the 1st slot in the signature mentioned in the bug report; I assume that would get fixed as part of the bug as well?

**Comment by gkossakowski** [comment]
Yep, once we get rid of other classes in signature we'll end up with (implicit) java/lang/Object. However, I mentioned this in the ticket to make sure it's not overlooked.

Fortunately enough, this issue is fairly isolated and can be easily fixed as opposed to #4. However, I'm working on a spec for this issue too. Once specified what should happen, implementing it should be fairly straightforward.

**Comment by gkossakowski** [comment]
This has been fixed upstream. Closing.
